spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modern_bank?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  threads:
    virtual:
      enabled: true

server:
  port: 8080

jwt:
  secret: PG6aGzIz9S3ZvYdiPt98qetX6rGgMl2okDl7CU+2wKU=

  access-expiration: 3600000      # 1시간 (60 * 60 * 1000)
  refresh-expiration: 1209600000  # 14일 (14 * 24 * 60 * 60 * 1000)